import { Photo } from '@/content/types';
import { DEFAULT_ETSY_URL } from '@/config/purchase';

/**
 * Dummy Etsy URL from spec - used for all photos in v1
 */
const DUMMY_ETSY_URL =
    DEFAULT_ETSY_URL;

/**
 * Photo collection metadata
 * Images sourced from Cloudinary: Travel and TreePeople folders
 */
export const allPhotos: Photo[] = [
    // ============================================
    // STREET PHOTOGRAPHY - Tree People Series (8 photos)
    // ============================================
    {
        id: 'tree-people-01',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1014966_ialxay',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People I',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-02',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015086_dpbnjy',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People II',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-03',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1014970_aqajot',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People III',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-04',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015082_svfbbe',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People IV',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-05',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1014964_ddz4cq',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People V',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-06',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015045_slktjn',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People VI',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-07',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015048_nk22rg',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People VII',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 7855,
        height: 4418,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-08',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015007_punmgr',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People VIII',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },

    // ============================================
    // TRAVEL PHOTOGRAPHY (17 photos)
    // ============================================
    {
        id: 'travel-01',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-50_mckvtm',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista I',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-02',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1012316_igwhzc',
        alt: 'Travel photography landscape scene',
        title: 'Coastal Journey',
        category: 'travel',
        orientation: 'landscape',
        width: 7821,
        height: 5219,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-03',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-38_x20d9y',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista II',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-04',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1012384_v7uifg',
        alt: 'Travel photography landscape scene',
        title: 'Distant Shores',
        category: 'travel',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-05',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-53_x4n3fo',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista III',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-06',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-45_ffdw81',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista IV',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-07',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-37_ikyzjt',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait I',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-08',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-44_hivokp',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait II',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-09',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-35_p4g2lm',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista V',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-10',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-48_cpqqul',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait III',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-11',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-8_wij6p3',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista VI',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6691,
        height: 4437,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-12',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-13_foedfs',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait IV',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-13',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-11_qufore',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista VII',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6738,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-15',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738740_wbt2fy',
        alt: 'Travel photography landscape scene',
        title: 'Wanderlust I',
        category: 'travel',
        orientation: 'landscape',
        width: 5941,
        height: 3961,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-16',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738683_aqezk9',
        alt: 'Travel photography landscape scene',
        title: 'Wanderlust II',
        category: 'travel',
        orientation: 'landscape',
        width: 5740,
        height: 3827,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-17',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738409_c2rqd4',
        alt: 'Travel photography landscape scene',
        title: 'Wanderlust III',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },

    // ============================================
    // NEWLY INDEXED PHOTOS (54)
    // ============================================
    {
        id: '000010370015-wel6e3',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010370015_wel6e3',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010380012-lex8h3',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010380012_lex8h3',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010380017-rqem2w',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010380017_rqem2w',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010390007-xfkyio',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010390007_xfkyio',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010390017-qpwfst',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010390017_qpwfst',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010400005-tfnzgr',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010400005_tfnzgr',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010400026-jqvue6',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010400026_jqvue6',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 2948,
        height: 1954,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000010400029-tmvnur',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000010400029_tmvnur',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000016250028-ha9mtg',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000016250028_ha9mtg',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000016250036-bph1za',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000016250036_bph1za',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3055,
        height: 2025,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000016260004-lopai6',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000016260004_lopai6',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000044090003-oaxyka',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000044090003_oaxyka',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000044090017-piznjk',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000044090017_piznjk',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'portrait',
        width: 2075,
        height: 3130,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000080450025-gigoct',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000080450025_gigoct',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000092900007-whjym8',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000092900007_whjym8',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3013,
        height: 1997,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '000092900022-rf96k4',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '000092900022_rf96k4',
        alt: 'Film Scans photograph captured on digital',
        title: 'Film Scans I',
        category: 'moments',
        series: 'Film Scans',
        orientation: 'landscape',
        width: 3130,
        height: 2075,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'l1001817-aidmb1',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1001817_aidmb1',
        alt: 'street photograph captured on digital',
        title: 'street I',
        category: 'street',
        orientation: 'landscape',
        width: 7566,
        height: 5049,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'l1001820-vskf0y',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1001820_vskf0y',
        alt: 'street photograph captured on digital',
        title: 'street I',
        category: 'street',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'l1001877-suozqb',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1001877_suozqb',
        alt: 'street photograph captured on digital',
        title: 'street I',
        category: 'street',
        orientation: 'landscape',
        width: 7520,
        height: 5018,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'l1011353-nsgfsy',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1011353_nsgfsy',
        alt: 'street photograph captured on digital',
        title: 'street I',
        category: 'street',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'l1012027-cqujut',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1012027_cqujut',
        alt: 'street photograph captured on digital',
        title: 'street I',
        category: 'street',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a733931-vjjbiz',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A733931_vjjbiz',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734187-p2lv59',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734187_p2lv59',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 4624,
        height: 3083,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734191-ghbbfh',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734191_ghbbfh',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734481-e59nuk',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734481_e59nuk',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734541-aq8sb2',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734541_aq8sb2',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 4827,
        height: 3218,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734552-hvdmfo',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734552_hvdmfo',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 5009,
        height: 2818,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734815-k5x7jp',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734815_k5x7jp',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 5743,
        height: 3829,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a734891-entyqy',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A734891_entyqy',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'portrait',
        width: 4000,
        height: 6000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a737358-jokwv2',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A737358_jokwv2',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a737448-jjrxn3',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A737448_jjrxn3',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'portrait',
        width: 4000,
        height: 6000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a738288-a8rkke',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738288_a8rkke',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a738514-pano-hju8ip',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738514-Pano_hju8ip',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 14135,
        height: 3512,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: '-a738523-k6p1jg',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738523_k6p1jg',
        alt: 'travel photograph captured on digital',
        title: 'travel I',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'mexico-day3-110-qofyit',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'MEXICO_DAY3_110_qofyit',
        alt: 'Mexico 2024 photograph captured on digital',
        title: 'Mexico 2024 I',
        category: 'travel',
        series: 'Mexico 2024',
        orientation: 'landscape',
        width: 4141,
        height: 2770,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'mexico-day8-5-vxx2wh',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'MEXICO_DAY8_5_vxx2wh',
        alt: 'Mexico 2024 photograph captured on digital',
        title: 'Mexico 2024 I',
        category: 'travel',
        series: 'Mexico 2024',
        orientation: 'landscape',
        width: 6240,
        height: 4160,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'mexico-day9-8-vgllci',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'MEXICO_DAY9_8_vgllci',
        alt: 'Mexico 2024 photograph captured on digital',
        title: 'Mexico 2024 I',
        category: 'travel',
        series: 'Mexico 2024',
        orientation: 'portrait',
        width: 3776,
        height: 5664,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'mexico-day9-89-vsmm6b',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'MEXICO_DAY9_89_vsmm6b',
        alt: 'Mexico 2024 photograph captured on digital',
        title: 'Mexico 2024 I',
        category: 'travel',
        series: 'Mexico 2024',
        orientation: 'portrait',
        width: 4160,
        height: 6240,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-1-11-mhu01v',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_1-11_mhu01v',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6250,
        height: 4167,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-1-4-o8taod',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_1-4_o8taod',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 7008,
        height: 4672,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-1-6-fzetfw',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_1-6_fzetfw',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6678,
        height: 4452,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-10-11-exzm8n',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_10-11_exzm8n',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 7008,
        height: 4672,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-10-15-khzzwh',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_10-15_khzzwh',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'portrait',
        width: 4672,
        height: 7008,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-2-7-gkufiy',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_2-7_gkufiy',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 7008,
        height: 4672,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-6-11-ho6zof',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_6-11_ho6zof',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6716,
        height: 4477,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-7-5-jbnnzu',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_7-5_jbnnzu',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 7008,
        height: 4672,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-day-8-10-i38sv3',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_DAY_8-10_i38sv3',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 7008,
        height: 4672,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-14-kluzmw',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-14_kluzmw',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 5605,
        height: 3717,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-20-nnqtte',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-20_nnqtte',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-24-yobrm0',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-24_yobrm0',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-25-kreijo',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-25_kreijo',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-29-mnelsk',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-29_mnelsk',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-33-y4c12d',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-33_y4c12d',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'portrait',
        width: 4340,
        height: 6545,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'thailand-2024-film-6-cnolph',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'THAILAND_2024_FILM-6_cnolph',
        alt: 'Thailand 2024 photograph captured on digital',
        title: 'Thailand 2024 I',
        category: 'travel',
        series: 'Thailand 2024',
        orientation: 'landscape',
        width: 6522,
        height: 3669,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
];
