import { Photo } from './types';

/**
 * Dummy Etsy URL from spec - used for all photos in v1
 */
const DUMMY_ETSY_URL =
    'https://www.etsy.com/listing/1421980161/muir-woods-and-fern-creek-photo-redwood?ls=s&ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=photo+prints&ref=sr_gallery-1-39&sr_prefetch=1&pf_from=search&pro=1&frs=1&sts=1&content_source=8c92eca6-47d3-4501-b00e-3412fa50f615%253ALT376b5942c26e3adec6a78eb5175edbcb614a11f3&organic_search_click=1&logging_key=8c92eca6-47d3-4501-b00e-3412fa50f615%3ALT376b5942c26e3adec6a78eb5175edbcb614a11f3&variation0=3273691037';

/**
 * Photo collection metadata
 * Images sourced from Cloudinary: Travel and TreePeople folders
 */
export const photos: Photo[] = [
    // ============================================
    // STREET PHOTOGRAPHY - Tree People Series (8 photos)
    // ============================================
    {
        id: 'tree-people-01',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1014966_ialxay',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People I',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-02',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015086_dpbnjy',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People II',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-03',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1014970_aqajot',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People III',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-04',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015082_svfbbe',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People IV',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-05',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1014964_ddz4cq',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People V',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-06',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015045_slktjn',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People VI',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-07',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015048_nk22rg',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People VII',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 7855,
        height: 4418,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'tree-people-08',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1015007_punmgr',
        alt: 'Tree People environmental portrait in natural setting',
        title: 'Tree People VIII',
        category: 'street',
        series: 'Tree People',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },

    // ============================================
    // TRAVEL PHOTOGRAPHY (17 photos)
    // ============================================
    {
        id: 'travel-01',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-50_mckvtm',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista I',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-02',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1012316_igwhzc',
        alt: 'Travel photography landscape scene',
        title: 'Coastal Journey',
        category: 'travel',
        orientation: 'landscape',
        width: 7821,
        height: 5219,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-03',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-38_x20d9y',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista II',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-04',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'L1012384_v7uifg',
        alt: 'Travel photography landscape scene',
        title: 'Distant Shores',
        category: 'travel',
        orientation: 'landscape',
        width: 8368,
        height: 5584,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-05',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-53_x4n3fo',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista III',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-06',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-45_ffdw81',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista IV',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-07',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-37_ikyzjt',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait I',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: true,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-08',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-44_hivokp',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait II',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-09',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-35_p4g2lm',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista V',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6774,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-10',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-48_cpqqul',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait III',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-11',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-8_wij6p3',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista VI',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6691,
        height: 4437,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-12',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-13_foedfs',
        alt: 'Hawaii portrait orientation film photograph',
        title: 'Island Portrait IV',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'portrait',
        width: 4492,
        height: 6774,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-13',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-11_qufore',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista VII',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6738,
        height: 4492,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-14',
        src: '/photos/placeholder.jpg',
        cloudinaryId: 'HAWAII_2025_FILM-5_c9uica',
        alt: 'Hawaii landscape captured on film',
        title: 'Hawaiian Vista VIII',
        category: 'travel',
        series: 'Hawaii 2025',
        orientation: 'landscape',
        width: 6488,
        height: 4302,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-15',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738740_wbt2fy',
        alt: 'Travel photography landscape scene',
        title: 'Wanderlust I',
        category: 'travel',
        orientation: 'landscape',
        width: 5941,
        height: 3961,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-16',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738683_aqezk9',
        alt: 'Travel photography landscape scene',
        title: 'Wanderlust II',
        category: 'travel',
        orientation: 'landscape',
        width: 5740,
        height: 3827,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
    {
        id: 'travel-17',
        src: '/photos/placeholder.jpg',
        cloudinaryId: '_A738409_c2rqd4',
        alt: 'Travel photography landscape scene',
        title: 'Wanderlust III',
        category: 'travel',
        orientation: 'landscape',
        width: 6000,
        height: 4000,
        featured: false,
        etsyUrl: DUMMY_ETSY_URL,
    },
];
